spring.application.name=VoskAsync
server.port=0
vosk.model.path=${VOSK_MODEL_PATH:C:/vosk-model-small-ru-0.22}
vosk.handling.type=LOCAL
#vosk.handling.type=REMOTE
ffmpeg.path=${FFMPEG_PATH:ffmpeg}
ffprobe.path=${FFPROBE_PATH:ffprobe}
#RabbitMQ
spring.rabbitmq.host=${rabbitmq_host:localhost}
spring.rabbitmq.port=${rabbitmq_port:5672}
spring.rabbitmq.username=${rabbitmq_username:admin}
spring.rabbitmq.password=${rabbitmq_password:password}
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=2