spring.application.name=VoskAsync
vosk.model.path=${VOSK.MODEL.PATH:D:/vosk-model-small-ru-0.22}
vosk.handling.type=LOCAL
#vosk.handling.type=REMOTE

#RabbitMQ
spring.rabbitmq.host=${rabbitmq.host:localhost}
spring.rabbitmq.port=${rabbitmq.port:5672}
spring.rabbitmq.username=${rabbitmq.username:admin}
spring.rabbitmq.password=${rabbitmq.password:password}

spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=2