spring:
  kafka:
    bootstrap-servers: localhost:9092
    # === CONSUMER ===
    consumer:
      group-id: speech-workers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      max-poll-records: 500
      fetch-min-bytes: 1024
      fetch-max-wait: 500
    # === PRODUCER ===
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 10
      retry.backoff.ms: 500
      max.in.flight.requests.per.connection: 1
      delivery.timeout.ms: 120000
      request.timeout.ms: 30000
      compression.type: snappy
      batch.size: 16384
      linger.ms: 5
      buffer.memory: 33554432