spring:
  application:
    name: VoskAsync
  rabbitmq:
    host: ${rabbitmq.host:localhost}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:admin}
    password: ${rabbitmq.password:password}
  task:
    execution:
      pool:
        core-size: 2
        max-size: 2

vosk:
  model:
    path: ${VOSK.MODEL.PATH:C:/vosk-model-small-ru-0.22}
  handling:
    type: REMOTE
    # type: LOCAL